export const SCREEN_CHANGED = 'SCREEN_CHANGED';

export const USERNAME_CHANGED = 'USERNAME_CHANGED';

export const PLAYER_JOINED = 'PLAYER_JOINED';
export const PLAYER_READY = 'PLAYER_READY';

export const ROOMS_LIST_CHANGED = 'ROOMS_LIST_CHANGED';
export const ROOM_JOINED = 'ROOM_JOINED';
export const WAITING_ROOM_ENTERED = 'WAITING_ROOM_ENTERED';
export const GAME_STARTED = 'GAME_STARTED';

export const CONNECTED = 'CONNECTED';
export const DISCONNECTED = 'DISCONNECTED';

export const SELECTION_UPDATE = 'SELECTION_UPDATE';