export const NAVIGATION_CHANGED = 'NAVIGATION_CHANGED';

export const USERNAME_CHANGED = 'USERNAME_CHANGED';

export const PLAYER_JOINED = 'PLAYER_JOINED';

export const ROOMS_LIST_CHANGED = 'ROOMS_LIST_CHANGED';
export const ROOM_JOINED = 'ROOM_JOINED';
export const WAITING_ROOM_ENTERED = 'WAITING_ROOM_ENTERED';